# https://github.com/NVlabs/timeloop/blob/master/problem-shapes/gemm_ABZ.yaml

problem:
  shape:
    name: "gemm_ABZ"
    dimensions: [ M, N, K ]
    data_spaces:
      - name: Inputs
        projection:
          - [ [ M ] ]
          - [ [ K ] ]
      - name: Weights
        projection:
          - [ [ K ] ]
          - [ [ N ] ]
      - name: Outputs
        projection:
          - [ [ M ] ]
          - [ [ N ] ]
        read_write: True

  instance:
    M: 0
    N: 0
    K: 0